### ISSUE TITLE
Playing Local Songs -- MPV: [error] cplayer: Can not open external file **.lrc

### ISSUE THREAD

**Issue by FlamingoZxeK** [Pato05/just_audio_media_kit#20]
When playing a local song, if there happens to be a file with the same name but with a .lrc extension, the following error is printed: MPV: [error] cplayer: Can not open external file **.lrc, and the song cannot be played. Once the lyric file is deleted, the song can be played. I have tested this on both Windows 11 and macOS, and the issue persists on both platforms. I hope this can be fixed soon.

Here is the key code:

```
dependencies:
  just_audio: ^0.9.41
  just_audio_media_kit: ^2.0.5
  media_kit_libs_linux: any
  media_kit_libs_macos_audio: any
  media_kit_libs_windows_audio: any
```

`JustAudioMediaKit.ensureInitialized(windows: true, linux: true, macOS: true);`

```
final player = AudioPlayer()
player.setAudioSource(AudioSource.uri(Uri.file(filePath))).then((value) {
        player.play();
      });
```
